channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - git
  - bash_kernel
  - tzdata
  - csvkit
  - tree
  - bowtie2=2.5.1
  - fastp=0.23.2
  - pigz=2.6
  - samtools=1.17
  - fastqc=0.11.9
  - kraken2=2.1.3
  - pigz=2.6
  - r-nonpareil=3.4.0
  - r-argparse=2.2.2
  - r-tidyverse=2.0.0
  - samtools=1.17
  - multiqc=1.14
  - gzip=1.12
  - nonpareil=3.4.1
  - coreutils=9.3
  - bird_tool_utils_python=0.4.1
  - coverm=0.6.1
  - diamond=2.1.8  # singlem
  - hmmer=3.3.2  # singlem
  - orfm=1.3  # singlem
  - smafa=0.7.1  # singlem
  - krona=2.8.1  # singlem
  - pyranges=0.0.129  # singlem
  - pip:
    - zenodo_backpack==0.2.0
    - "--editable=git+https://github.com/wwood/singlem.git@bf259fba764a8da59ee43dbd47b39da6cd2d9563#egg=singlem"

